# Generated by Django 4.2.14 on 2024-09-05 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genre_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='genre',
            table='genre',
        ),
    ]
